### ISSUE TITLE
Web Route Setting

### ISSUE THREAD

**Issue by lydiuhoh** [CreativeSolutionLabs/careertalk-frontend#2]
## Story
Setup skeleton of react routing system.

## Details
**Public routes**
- Home: `/`
- About Career Talk: `/about`
- Get Involved: TBD

**Private routes**
- Featured: `/featured`
- Fairs: `/fairs`
- Employer Page: `/employer/1`
- Me:`/{USER_NAME}`
- Favorites: `/{USER_NAME}/favorites`

**Comment by junlee91** [comment]
Base routing setup is done.
