### ISSUE TITLE
Research Data Store & State Management

### ISSUE THREAD

**Issue by lydiuhoh** [CreativeSolutionLabs/careertalk-frontend#4]
**Context:**
Should we use Redux? Should we substitute?

**AC:**
- Documentation
- Architecture
- Team Architecture Review

**Comment by junlee91** [comment]
I think we should keep using Redux by following reasons: 
- already have some implementations from the mobile app, so migration would be easy
- concurrently manage the redux used in both platforms (web, mobile)
- better knowledge in redux than other substitutes 

There are some alternatives of redux: React Context API or GraphQL. 

Our app requires many api calls and data manipulations (employers, like, note, etc.), so Context API would not be a good solution.

GraphQL is getting popular and this might reduce the complexity of the app, but will have some learning curve & we will also have to refactor the backend part or we will need to develop another project for GraphQL. 

Example request flow: `Web <--> GraphQL <--> Flask server`

@sonamoo @hmx789

**Comment by junlee91** [comment]
Just writing some thoughts that we might not use redux. Still researching.

**Comment by junlee91** [comment]
We'll use the GraphQL for storage and handle API call.
